Repository onosproject/onos-ric, pull requests merged in 2020-04, with the labels that each got.

#176 Use common CLI base classes from onos-lib-go
  go.mod
  pkg/cli/config.go
  pkg/cli/handover.go
  pkg/cli/output.go
  pkg/cli/power.go
  pkg/cli/root.go
  pkg/cli/stationlinks.go
  pkg/cli/stations.go
  pkg/cli/uelinks.go
Labels: enhancement

#184 Updated documentation for use with docs website
  build/bin/compile-protos.sh
  docs/README.md
  docs/api/c1-interface.md
  docs/api/e2-interface.md
  docs/api/e2ap.md
  docs/api/e2sm.md
  docs/deployment.md
  docs/handover.md
  docs/loadbalancer.md
Labels: documentation

#189 Added target to bump onos dependencies for go
  Makefile
Labels: enhancement

#205 Add Ecid and crnti fields to header of E2 control messages
  api/sb/e2sm/e2sm.pb.go
  api/sb/e2sm/e2sm.proto
  docs/api/e2sm.md
  pkg/southbound/e2.go
Labels: enhancement

#207 Add a new bi-directional stream rpc to E2 proto
  api/sb/e2ap/e2ap.pb.go
  api/sb/e2ap/e2ap.proto
  api/sb/e2sm/e2sm.pb.go
  api/sb/e2sm/e2sm.proto
  docs/api/e2ap.md
  docs/api/e2sm.md
Labels: enhancement

#210 Fix broken ListStations
  pkg/manager/manager.go
  pkg/southbound/e2.go
Labels: bug

#211 Single gRPC stream E2
  build/generate/stores.yaml
  pkg/manager/manager.go
  pkg/northbound/c1/c1.go
  pkg/southbound/e2.go
  pkg/store/control/id.go
  pkg/store/control/interface.go
  pkg/store/control/store.go
Labels: enhancement

#222 Add coverage stubs for packages without any tests
  pkg/config/config_test.go
  pkg/exporter/exporter_test.go
  pkg/manager/manager_test.go
  pkg/northbound/c1/c1_test.go
  pkg/southbound/monitor/topo_test.go
  pkg/southbound/southbound_test.go
  pkg/store/control/store_test.go
  pkg/store/device/store_test.go
  pkg/store/message/store_test.go
Labels: DO_NOT_MERGE

#236 Unit tests for onos-ric northbound APIs
  go.mod
  pkg/manager/manager.go
  pkg/northbound/c1/c1_test.go
  pkg/northbound/c1/e2_mock_test.go
  pkg/northbound/c1/indications_store_mock_test.go
Labels: enhancement

#248 Initial commit for E2 configuration
  Makefile
  api/sb/e2-interface.pb.go
  api/sb/e2-interface.proto
  docs/api/e2-interface.md
  pkg/config/e2_config.go
  pkg/config/interface.go
  pkg/manager/manager.go
  pkg/northbound/c1/c1_test.go
  pkg/southbound/e2.go
  pkg/southbound/interface.go
  test/mocks/southbound/e2_mock.go
Labels: enhancement
