Repository onosproject/onos-ric, pull requests merged in 2020-02, with the labels that each got.

#15 Add CellConfigRequest/Report message #14
  pkg/southbound/e2.go
Labels: enhancement

#20 Added in support for onos-cli with just a stubbed out implementation
  go.mod
  go.sum
  pkg/cli/client.go
  pkg/cli/completion.go
  pkg/cli/config.go
  pkg/cli/crud.go
  pkg/cli/output.go
  pkg/cli/root.go
  pkg/cli/root_test.go
  pkg/cli/stationlinks.go
  pkg/cli/stations.go
  pkg/cli/uelinks.go
  pkg/cli/ues.go
Labels: enhancement

#29 Define IMSI number in UELinkInfo to allow apps to use UE's unique ID if necessary
  api/nb/c1-interface.proto
Labels: enhancement

#30 Remove ListUes cmd as removed from c1.proto
  api/nb/c1-interface.pb.go
  api/nb/c1-interface.proto
  docs/README.md
  docs/deployment.md
  go.mod
  go.sum
  pkg/cli/crud.go
  pkg/cli/stationlinks.go
  pkg/cli/stations.go
  pkg/cli/uelinks.go
  pkg/cli/ues.go
  pkg/northbound/c1/c1.go
Labels: bug

#42 Implement ListUEs NB function
  pkg/manager/manager.go
  pkg/northbound/c1/c1.go
Labels: DO_NOT_MERGE, enhancement

#49 minor E2/C1 proto changes for telemetry
  api/nb/c1-interface.pb.go
  api/nb/c1-interface.proto
  api/sb/e2-interface.pb.go
  api/sb/e2-interface.proto
  pkg/apps/onos-ran-ho/handover/handover.go
  pkg/apps/onos-ran-ho/handover/handover_test.go
  pkg/cli/uelinks.go
Labels: enhancement

#86 CLI UeLinks - changes the output to a tablematrix of Cells and UEs
  pkg/cli/uelinks.go
Labels: enhancement

#87 Ensure telemetry store test is deterministic
  pkg/store/telemetry/store_test.go
Labels: bug

#88 Add a simple benchmark for get stations
  Makefile
  benchmark/c1/stations.go
  benchmark/c1/suite.go
  build/bin/push-images
  build/onos-ran-benchmarks/Dockerfile
  cmd/onos-ran-benchmarks/main.go
Labels: enhancement

#102 add prometheus exporter in HO app
  build/grafana/ho-app-dashboard.json
  cmd/apps/onos-ric-ho/onos-ric-ho.go
  go.mod
  go.sum
  pkg/apps/onos-ric-ho/exporter/exporter.go
  pkg/apps/onos-ric-ho/southbound/c1.go
Labels: enhancement
