Repository onosproject/onos-ric, pull requests merged in 2020-05, with the labels that each got.

#254 Update HO app to have HO parameters - Hysteresis, A3Offset, and TTT
  cmd/apps/onos-ric-ho/onos-ric-ho.go
  pkg/apps/onos-ric-ho/handover/handover.go
  pkg/apps/onos-ric-ho/southbound/c1.go
Labels: enhancement

#259 Fix CQI delta calculation function
  pkg/apps/onos-ric-ho/handover/handover.go
Labels: bug

#258 Protobuf msg definitions for E2 subscription
  api/sb/e2ap/e2ap.pb.go
  api/sb/e2ap/e2ap.proto
  api/sb/e2sm/e2sm.pb.go
  api/sb/e2sm/e2sm.proto
  docs/api/e2ap.md
  docs/api/e2sm.md
Labels: enhancement

#252 Unit tests for the manager package
  go.mod
  go.sum
  pkg/config/config.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  test/mocks/store/device/store_mock.go
Labels: Testing

#261 Break deadlock problem in HO app
  pkg/apps/onos-ric-ho/handover/handover.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: bug

#267 Add test code for HO app to expand test coverage
  pkg/apps/onos-ric-ho/handover/handover.go
  pkg/apps/onos-ric-ho/handover/handover_test.go
Labels: Testing

#276 Modify HO app test code and Add MLB app test code
  pkg/apps/onos-ric-ho/handover/handover.go
  pkg/apps/onos-ric-ho/handover/handover_test.go
  pkg/apps/onos-ric-mlb/mlb/mlb_test.go
Labels: Testing

#281 Bugfix to send ueinfo to A3Event when sCell becomes the best cell in TTT
  pkg/apps/onos-ric-ho/handover/handover.go
  pkg/apps/onos-ric-ho/handover/handover_test.go
Labels: bug

#278 Improve coverage for RicControl APIs
  pkg/manager/manager_test.go
Labels: Testing, WIP
